# Generated by Django 4.2.3 on 2023-08-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randombox', '0001_initial'),
        ('users', '0002_customuser_p_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randombox.brand'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randombox.general'),
        ),
    ]
