# Generated by Django 4.2.3 on 2023-08-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randombox', '0001_initial'),
        ('users', '0003_customuser_brand_customuser_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='general',
        ),
        migrations.AddField(
            model_name='customuser',
            name='general',
            field=models.ManyToManyField(to='randombox.general'),
        ),
    ]
