# Generated by Django 4.2.3 on 2023-08-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contnet',
            new_name='content',
        ),
    ]
