# Generated by Django 4.2.3 on 2023-08-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock_qty', models.IntegerField(verbose_name='재고수량')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock_qty', models.IntegerField(verbose_name='재고수량')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
