# Generated by Django 4.2.3 on 2023-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randombox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain_sales', models.IntegerField(blank=True, null=True, verbose_name='남은 매출')),
            ],
        ),
    ]
