# Generated by Django 4.2.3 on 2023-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randombox', '0002_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='remain_sales',
            field=models.IntegerField(default=0, verbose_name='남은 매출'),
        ),
    ]
