# Generated by Django 4.2.3 on 2023-07-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contet',
            new_name='content',
        ),
    ]
