# Generated by Django 4.2.3 on 2023-08-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_answer_view_count_questioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncount',
            name='ip',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questioncount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
