# Generated by Django 4.2.3 on 2023-08-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_questioncount_ip_alter_questioncount_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='view_count',
        ),
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
